import { createHash } from "node:crypto";
import type { QuantizedFrame } from "@blockdream/color-core";
import { computeDeltas } from "./delta";
import type { GeneratedPack } from "./datapack";

export interface BedrockScriptOptions {
  name?: string;
  description?: string;
  origin?: { x: number; y: number; z: number };
  speedTicks?: number;
  dimension?: "overworld" | "nether" | "the_end";
  autoplay?: boolean;
  minEngineVersion?: [number, number, number];
  serverModuleVersion?: string;
  uuids?: [string, string];
}

function uuidFromSeed(seed: string): string {
  const h = createHash("sha1").update(seed).digest("hex");
  const y = ((parseInt(h[16]!, 16) & 0x3) | 0x8).toString(16);
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-${y}${h.slice(17, 20)}-${h.slice(20, 32)}`;
}

/** Runtime player (Bedrock Script API). Mirrors mods/bedrock-addon/scripts/main.js. */
export const BEDROCK_PLAYER_JS = `import { world, system, BlockPermutation } from "@minecraft/server";
import { POOL } from "./frames.js";

let frameIndex = 0, tickCounter = 0, playing = POOL.autoplay ?? false;
const dim = () => world.getDimension(POOL.dimension ?? "overworld");

function applyFrame(f) {
  const d = dim(), cells = POOL.frames[f];
  for (let i = 0; i < cells.length; i++) {
    const c = cells[i], blockId = POOL.palette[c[2]];
    if (!blockId) continue;
    const loc = { x: POOL.origin.x + c[0], y: POOL.origin.y + (POOL.height - 1 - c[1]), z: POOL.origin.z };
    const block = d.getBlock(loc);
    if (block) { try { block.setPermutation(BlockPermutation.resolve(blockId)); } catch {} }
  }
}
function reset() { frameIndex = 0; tickCounter = 0; applyFrame(0); }

system.runInterval(() => {
  if (!playing || POOL.frames.length === 0) return;
  if (++tickCounter < POOL.speedTicks) return;
  tickCounter = 0;
  frameIndex = (frameIndex + 1) % POOL.frames.length;
  applyFrame(frameIndex);
});

// Frames are delta-encoded (frame 0 is the full keyframe, later frames only the
// changed cells). Draw frame 0 once on load - deferred a tick so the world is
// ready - so autoplay starts from the keyframe instead of applying frame 1's
// delta onto an empty wall. (Manual !mw start calls reset() itself.)
system.run(() => { if (playing) reset(); });

world.afterEvents.chatSend?.subscribe((ev) => {
  const msg = ev.message.trim();
  if (!msg.startsWith("!mw")) return;
  const cmd = msg.slice(3).trim();
  if (cmd === "start") { reset(); playing = true; ev.sender.sendMessage("§a[blockdream] playing"); }
  else if (cmd === "stop") { playing = false; ev.sender.sendMessage("§e[blockdream] stopped"); }
  else if (cmd === "reset") { reset(); ev.sender.sendMessage("§b[blockdream] reset"); }
});
`;

/** Serialize frames to the POOL data module (frames.js) consumed by the player. */
export function buildFramesJs(
  frames: QuantizedFrame[],
  resolveBlock: (mapColorId: number) => string | undefined,
  opts: BedrockScriptOptions,
): string {
  const origin = opts.origin ?? { x: 0, y: 64, z: 0 };
  const speed = Math.max(1, Math.floor(opts.speedTicks ?? 2));
  const { height } = frames[0]!;
  const deltas = computeDeltas(frames);

  // intern block ids into a palette; cells reference palette indices
  const paletteIndex = new Map<string, number>();
  const palette: string[] = [];
  const intern = (id: string): number => {
    let i = paletteIndex.get(id);
    if (i === undefined) {
      i = palette.length;
      paletteIndex.set(id, i);
      palette.push(id);
    }
    return i;
  };

  const fallback = "minecraft:air";
  const frameCells = deltas.map((d) =>
    d.cells.map((c) => [c.x, c.y, intern(resolveBlock(c.mapColorId) ?? fallback)]),
  );

  const pool = {
    height,
    origin,
    speedTicks: speed,
    dimension: opts.dimension ?? "overworld",
    autoplay: opts.autoplay ?? false,
    palette,
    frames: frameCells,
  };
  return `// generated by @blockdream/emit-commands - block-art delta frames\nexport const POOL = ${JSON.stringify(pool)};\n`;
}

/**
 * Generate a complete Bedrock Script-API behavior pack that animates a block
 * wall. This is Bedrock's best-available "native" real-time path (the Script API
 * cannot paint map items, so video-on-maps is not reachable in vanilla Bedrock).
 */
export function generateBedrockScriptAddon(
  frames: QuantizedFrame[],
  resolveBlock: (mapColorId: number) => string | undefined,
  opts: BedrockScriptOptions = {},
): GeneratedPack {
  if (frames.length === 0) throw new Error("no frames");
  const { width: W, height: H } = frames[0]!;
  const files = new Map<string, string>();

  files.set("behavior_pack/scripts/main.js", BEDROCK_PLAYER_JS);
  files.set("behavior_pack/scripts/frames.js", buildFramesJs(frames, resolveBlock, opts));

  const headerUuid = opts.uuids?.[0] ?? uuidFromSeed("blockdream-script:header");
  const moduleUuid = opts.uuids?.[1] ?? uuidFromSeed("blockdream-script:module");
  files.set(
    "behavior_pack/manifest.json",
    JSON.stringify(
      {
        format_version: 2,
        header: {
          name: opts.name ?? "blockdream Block-Art Player",
          description: opts.description ?? `${W}×${H}, ${frames.length} frames`,
          uuid: headerUuid,
          version: [0, 1, 0],
          min_engine_version: opts.minEngineVersion ?? [1, 21, 0],
        },
        modules: [
          {
            type: "script",
            language: "javascript",
            uuid: moduleUuid,
            version: [0, 1, 0],
            entry: "scripts/main.js",
          },
        ],
        dependencies: [{ module_name: "@minecraft/server", version: opts.serverModuleVersion ?? "1.14.0" }],
      },
      null,
      2,
    ) + "\n",
  );

  let totalSetblocks = 0;
  for (const d of computeDeltas(frames)) totalSetblocks += d.cells.length;
  return { files, namespace: "blockdream", frameCount: frames.length, width: W, height: H, totalSetblocks };
}
